stages:
  - prepare-environment
  - build

prepare-environment:
  stage: prepare-environment
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:latest
  script:
    - cd scripts
    - export IMAGE_TAG=$IMAGE_PREFIX/gaffa-buildenv
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $IMAGE_TAG
    # Use old image if existent to use build caching (if available)
    - docker pull $IMAGE_TAG || true
    - docker pull openwrtorg/sdk:mvebu-cortexa9-22.03.3
    - if [ -f "pre_build_hook" ]; then ./pre_build_hook; fi
    - docker build --cache-from $IMAGE_TAG --allow network.host -t $IMAGE_TAG -f Dockerfile .
    - docker push $IMAGE_TAG
