
name: Build Binaries

on:
  push:
    branches-ignore:
      - "main"

jobs:
  get-new-version:
    permissions:
      contents: read
    uses: ./.github/workflows/get-version.yml

  debug:
    runs-on: ubuntu-latest
    needs:
      [get-new-version]
    steps:
      - run: echo ${{ needs.get-new-version.outputs.version }}

  build-arm:
    permissions:
      packages: write
      contents: read
    needs:
      [get-new-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
      version: ${{needs.get-new-version.outputs }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  build-ramips:
    permissions:
      packages: write
      contents: read
    needs:
      [get-new-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
      version: ${{needs.get-new-version.outputs }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
