
name: Build Binaries

on:
  push:

jobs:
  build-arm:
    uses: ./.github/workflows/build-binary-template.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}

  build-ramips:
    uses: ./.github/workflows/build-binary-template.yml
    with:
      architecture: ramips-mt7621-22.03.3
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
