
name: Build Binaries

on:
  push:
    branches-ignore:
      - "main"

jobs:
  get-version:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    permissions:
      contents: read
    steps:
      - id: semver
        uses: ./.github/workflows/get-version.yml
      - run: echo "${{ steps.semver.outputs.version}}"
      - id: step1
        run: echo "version=${{ steps.semver.outputs.version}}" >> "$GITHUB_OUTPUT"
  build-arm:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  build-ramips:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
