
name: Build Binaries

on:
  push:
    branches-ignore:
      - "main"

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: get
        uses: ./.github/workflows/get-version.yml
      - id: step1
        run: echo "version=${{ steps.get.outputs.version }}" >> "$GITHUB_OUTPUT"

  build-arm:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  build-ramips:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
