
name: Build Binaries

on:
  push:
    branches-ignore:
      - "main"

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        #with:
        #  #fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        #  prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - run: echo "${{ steps.previoustag.outputs.tag }}"
      - id: step1
        run: echo "version=${{ steps.semvers.outputs.v_patch }}" >> "$GITHUB_OUTPUT"
  build-arm:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  build-ramips:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
