name: Build OpenWRT Image

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
    secrets:
      ghtoken:
        required: true

jobs:
  build-env:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ghtoken }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        pull: true
        context: ./scripts
        tags: ghcr.io/wimove-oss/wimove/wimove-buildenv/${{ inputs.architecture }}:${{ env.BRANCH }}
        cache-from: ghcr.io/wimove-oss/wimove/wimove-buildenv/${{ inputs.architecture }}:${{ env.BRANCH }}
        build-args: |
          TAG=${{ inputs.architecture }}
    - name: Build Binary
      run: export IMAGE="ghcr.io/wimove-oss/wimove/wimove-buildenv/${{ inputs.architecture }}:${{ env.BRANCH }}" && chmod +x ./scripts/build-gha.sh && ./scripts/build-gha.sh
