name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: false
        context: ./scripts
        tags: wimove-buildenv/arm:${{ env.BRANCH }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Run Build script
      run: cd scripts && chmod +x build-gha.sh && ./build-gha.sh
    - uses: actions/upload-artifact@v3
      with:
          name: wimove-arm.ipk
          path: out/*.ipk
