name: Build OpenWRT Image

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./scripts
        tags: ghcr.io/wimove-oss/wimove/wimove-buildenv/arm:${{ env.BRANCH }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  binary:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wimove-oss/wimove/wimove-buildenv/arm:github-ci
    needs: build
    steps:
      - name: Test
        run: echo "Hello World"
