name: Run clang linter

on:
  push:
  pull_request:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start formatting
        run: find src -iname *.h -o -iname *.cpp | xargs clang-format -i
      - name: Start CMake
        run: cmake CMakeLists.txt
      - name: Start linting
        run: clang-tidy --config-file=.clang-tidy src/**/*.h src/**/*.cpp -p compile_commands.json
