name: Run clang linter

on:
  push:
  pull_request:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Start formatting
        run: find src -iname *.h -o -iname *.cpp | xargs clang-format -i
      - name: Clone prometheus-cpp
        run: gh repo clone ArcherMarkI/prometheus-cpp
      - name: Build prometheus-cpp
        run: git submodule init && git submodule update && cd _build && cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF && cmake --build . --parallel 4 && ctest -V && cmake --install . 
      - name: Start CMake
        run: cmake CMakeLists.txt
      - name: Start linting
        run: clang-tidy --config-file=.clang-tidy src/**/*.h src/**/*.cpp -p compile_commands.json
