name: Run clang linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start linting
        run: find src -iname *.h -o -iname *.cpp | xargs clang-format -i
