
name: Build Releases

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"
jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
  build-arm:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  build-ramips:
    permissions:
      packages: write
      contents: read
    needs:
      [get-version]
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
      version: ${{needs.get-version.outputs.version }}
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
  pre-release:
    needs: [build-ramips, build-arm]
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/download-artifact@v3
      - name: Move all files into current working directory
        run: "mv */*.ipk ."
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "*.ipk"
