
name: Build Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-arm:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: mvebu-cortexa9-22.03.3
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}

  build-ramips:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-openwrt.yml
    with:
      architecture: ramips-mt7621-22.03.3
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}

  pre-release:
    needs: [build-ramips, build-arm]
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/download-artifact@v3
      - name: Move all files into current working directory
        run: "mv */*.ipk ."
      - name: Rename Files to contain commit hash
        run: |
          for file in *.ipk; do
            mv "$file" "${file%.ipk}_${{ github.sha }}.ipk"
          done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "*.ipk"
