
name: Build Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-arm:
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: ./.github/workflows/build-openwrt.yml
        with:
          architecture: mvebu-cortexa9-22.03.3
          version: ${{ env.RELEASE_VERSION }}
        secrets:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

  build-ramips:
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: ./.github/workflows/build-openwrt.yml
        with:
          architecture: ramips-mt7621-22.03.3
          version: ${{ env.RELEASE_VERSION }}
        secrets:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [build-ramips, build-arm]
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/download-artifact@v3
      - name: Move all files into current working directory
        run: "mv */*.ipk ."
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "*.ipk"
